package com.lili.domain;
// Generated 2019-1-12 21:11:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GameInfo generated by hbm2java
 */
@Entity
@Table(name = "game_info", catalog = "vcdb")
public class GameInfo implements java.io.Serializable {

	private Integer id;
	private int gcId;
	private String name;
	private String detail;
	private Date createTime;
	private Date updateTime;

	public GameInfo() {
	}

	public GameInfo(int gcId, String name) {
		this.gcId = gcId;
		this.name = name;
	}

	public GameInfo(int gcId, String name, String detail, Date createTime, Date updateTime) {
		this.gcId = gcId;
		this.name = name;
		this.detail = detail;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "gc_id", nullable = false)
	public int getGcId() {
		return this.gcId;
	}

	public void setGcId(int gcId) {
		this.gcId = gcId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "detail", length = 65535)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
