package com.lili.domain;
// Generated 2019-1-12 16:46:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GameClass generated by hbm2java
 */
@Entity
@Table(name = "game_class", catalog = "vcdb")
public class GameClass implements java.io.Serializable {

	private Integer id;
	private String gameCname;
	private Integer status;
	private Date createTime;
	private Date updateTime;

	public GameClass() {
	}

	public GameClass(String gameCname, Integer status, Date createTime, Date updateTime) {
		this.gameCname = gameCname;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "game_cname", length = 50)
	public String getGameCname() {
		return this.gameCname;
	}

	public void setGameCname(String gameCname) {
		this.gameCname = gameCname;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
