package com.lili.domain;
// Generated 2019-1-5 15:21:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GameUser generated by hbm2java
 */
@Entity
@Table(name = "game_user", catalog = "vcdb")
public class GameUser implements java.io.Serializable {

	private Integer id;
	private Integer gameId;
	private String name;
	private String niname;
	private Integer VAmount;
	private Integer status;
	private Date createTime;
	private Date updateTime;

	public GameUser() {
	}

	public GameUser(Integer gameId, String name, String niname, Integer VAmount, Integer status, Date createTime,
			Date updateTime) {
		this.gameId = gameId;
		this.name = name;
		this.niname = niname;
		this.VAmount = VAmount;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "game_id")
	public Integer getGameId() {
		return this.gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "niname")
	public String getNiname() {
		return this.niname;
	}

	public void setNiname(String niname) {
		this.niname = niname;
	}

	@Column(name = "v_amount")
	public Integer getVAmount() {
		return this.VAmount;
	}

	public void setVAmount(Integer VAmount) {
		this.VAmount = VAmount;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
