package com.lili.domain;
// Generated 2019-1-5 15:21:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pay generated by hbm2java
 */
@Entity
@Table(name = "pay", catalog = "vcdb")
public class Pay implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer VAmount;
	private Integer gameId;
	private Integer gameUserId;
	private Integer status;
	private Date payTime;

	public Pay() {
	}

	public Pay(Integer userId, Integer VAmount, Integer gameId, Integer gameUserId, Integer status, Date payTime) {
		this.userId = userId;
		this.VAmount = VAmount;
		this.gameId = gameId;
		this.gameUserId = gameUserId;
		this.status = status;
		this.payTime = payTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "v_amount")
	public Integer getVAmount() {
		return this.VAmount;
	}

	public void setVAmount(Integer VAmount) {
		this.VAmount = VAmount;
	}

	@Column(name = "game_id")
	public Integer getGameId() {
		return this.gameId;
	}

	public void setGameId(Integer gameId) {
		this.gameId = gameId;
	}

	@Column(name = "game_user_id")
	public Integer getGameUserId() {
		return this.gameUserId;
	}

	public void setGameUserId(Integer gameUserId) {
		this.gameUserId = gameUserId;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pay_time", length = 19)
	public Date getPayTime() {
		return this.payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

}
