package com.lili.domain;
// Generated 2019-2-9 18:19:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * RechargeOrder generated by hbm2java
 */
@Entity
@Table(name = "recharge_order", catalog = "vcdb", uniqueConstraints = @UniqueConstraint(columnNames = "out_trade_no"))
public class RechargeOrder implements java.io.Serializable {

	private Long id;
	private String outTradeNo;
	private Integer userId;
	private Integer rechargeUserId;
	private Integer VAmount;
	private Integer rmbAmount;
	private Integer status;
	private Integer checkStatus;
	private Date rechargeTime;
	private Date createTime;
	private Date updateTime;

	public RechargeOrder() {
	}

	public RechargeOrder(String outTradeNo, Integer userId, Integer rechargeUserId, Integer VAmount, Integer rmbAmount,
			Integer status, Integer checkStatus, Date rechargeTime, Date createTime, Date updateTime) {
		this.outTradeNo = outTradeNo;
		this.userId = userId;
		this.rechargeUserId = rechargeUserId;
		this.VAmount = VAmount;
		this.rmbAmount = rmbAmount;
		this.status = status;
		this.checkStatus = checkStatus;
		this.rechargeTime = rechargeTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "out_trade_no", unique = true)
	public String getOutTradeNo() {
		return this.outTradeNo;
	}

	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "recharge_user_id")
	public Integer getRechargeUserId() {
		return this.rechargeUserId;
	}

	public void setRechargeUserId(Integer rechargeUserId) {
		this.rechargeUserId = rechargeUserId;
	}

	@Column(name = "v_amount")
	public Integer getVAmount() {
		return this.VAmount;
	}

	public void setVAmount(Integer VAmount) {
		this.VAmount = VAmount;
	}

	@Column(name = "rmb_amount")
	public Integer getRmbAmount() {
		return this.rmbAmount;
	}

	public void setRmbAmount(Integer rmbAmount) {
		this.rmbAmount = rmbAmount;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "check_status")
	public Integer getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "recharge_time", length = 19)
	public Date getRechargeTime() {
		return this.rechargeTime;
	}

	public void setRechargeTime(Date rechargeTime) {
		this.rechargeTime = rechargeTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
